# Generated by Django 4.1.2 on 2022-10-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_person_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.CharField(max_length=150),
        ),
    ]
